### ISSUE TITLE
(IMPORTANT) avoid TMPDIR going stale

### ISSUE THREAD

**Issue by pmq20** [pmq20/node-compiler#42]
See .https://github.com/pmq20/node-compiler/issues/25

> Also, have you cleaned your temporary directory that the compiler uses? If old directory generated by nodec 0.x is used then it would be problematic. I should fix this this in a precautionary way.

**Comment by lexor90** [comment]
@pmq20 This is only partially avoidable at the moment, because the user can use the `--tmp-dir` option which would still be the same whenever you upgrade (assuming one is using it). So if I call nodec with `--tmp-dir=/tmp/myproj` any patch you'd put would result useless in this case.

A better solution IMO is to create an inner directory under the current `tmpdir` so that the resulting path is `/tmp/myproj/100/` where `100` is the current nodec version (semver

 *OR*

to place a metadata file such as `/tmp/myproj/status.txt` where we might store useful things (e.g. the timestamp for the last run, the version, and so on). We might use this metadata to auto-invalidate cache, perform more advanced things (e.g. incremental builds, or recompilation only if target has changed, plus and, obviously, to clean up when a newer (or simply different) version detects the tmpdir is not empty.

A fictionary status.txt might be as simple as

    VERSION=1.0.0

This would also be useful to store some debugging info (à la npm-debug.log).

**Comment by pmq20** [comment]
@lexor90 This is a very good point and the idea proposed looks very nice. Let me change the title to reflect this.

This very problem is now of a high priority as auto-update has been enabled since nodec v1.2.0. Nodec now checks with the latest version returned from the http://enclose.io server. This issue has to be resolved before releasing nodec v1.3.0; otherwise the auto-upgraded compile process will have a hard time dealing with strange errors since their tmpdir has gone stale.
